/** Thumbnails for the expansion basics parts, keyed by photoHint. Original illustrations: see public/photos/basics/README.md. */
export const EXTRA_BASICS_MEDIA: Record<string, string> = {
  "led-yellow": "/photos/basics/led-yellow.svg",
  "led-blue": "/photos/basics/led-blue.svg",
  "led-white": "/photos/basics/led-white.svg",
  "led-orange": "/photos/basics/led-orange.svg",
  "led-ir-940": "/photos/basics/led-ir-940.svg",
  "resistor-100": "/photos/basics/resistor-100.svg",
  "resistor-330": "/photos/basics/resistor-330.svg",
  "resistor-470": "/photos/basics/resistor-470.svg",
  "resistor-2k2": "/photos/basics/resistor-2k2.svg",
  "resistor-4k7": "/photos/basics/resistor-4k7.svg",
  "resistor-47k": "/photos/basics/resistor-47k.svg",
  "resistor-100k": "/photos/basics/resistor-100k.svg",
  "resistor-1m": "/photos/basics/resistor-1m.svg",
  "capacitor-ceramic-100nf": "/photos/basics/capacitor-ceramic-100nf.svg",
  "capacitor-electrolytic-10uf": "/photos/basics/capacitor-electrolytic-10uf.svg",
  "capacitor-electrolytic-100uf": "/photos/basics/capacitor-electrolytic-100uf.svg",
  "capacitor-electrolytic-1000uf": "/photos/basics/capacitor-electrolytic-1000uf.svg",
  "diode-1n4007": "/photos/basics/diode-1n4007.svg",
  "diode-1n4148": "/photos/basics/diode-1n4148.svg",
  "diode-1n5819": "/photos/basics/diode-1n5819.svg",
  "diode-zener-5v1": "/photos/basics/diode-zener-5v1.svg",
  "transistor-2n2222": "/photos/basics/transistor-2n2222.svg",
  "transistor-2n3904": "/photos/basics/transistor-2n3904.svg",
  "transistor-bc547": "/photos/basics/transistor-bc547.svg",
  "transistor-tip120": "/photos/basics/transistor-tip120.svg",
  "mosfet-irlz44n": "/photos/basics/mosfet-irlz44n.svg",
  "irf520-module": "/photos/basics/irf520-module.svg",
  "switch-toggle-spst": "/photos/basics/switch-toggle-spst.svg",
  "switch-rocker": "/photos/basics/switch-rocker.svg",
  "dc-jack-5521": "/photos/basics/dc-jack-5521.svg",
  "regulator-7805": "/photos/basics/regulator-7805.svg",
  "ams1117-33": "/photos/basics/ams1117-33.svg",
  "lm2596-module": "/photos/basics/lm2596-module.svg",
  "mt3608-module": "/photos/basics/mt3608-module.svg",
  "tp4056-usbc": "/photos/basics/tp4056-usbc.svg",
};
