// Generated by scripts/gen-battery-art.mjs. Do not edit by hand.
// Size of each drawing in public/assets/batteries and where its + and - wires attach.
import type { BatteryTerminals } from "./batteries";

export type BatteryGeometry = { width: number; height: number; terminals: BatteryTerminals };

export const BATTERY_GEOMETRY = {
  battery_1aa: {
    width: 120,
    height: 182,
    terminals: {
      plus: { x: 60, y: 10 },
      minus: { x: 60, y: 165 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: 1 },
    },
  },
  battery_4aa: {
    width: 216,
    height: 168,
    terminals: {
      plus: { x: 36, y: 10 },
      minus: { x: 180, y: 10 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_6aa: {
    width: 288,
    height: 168,
    terminals: {
      plus: { x: 34, y: 10 },
      minus: { x: 254, y: 10 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_2aaa: {
    width: 120,
    height: 154,
    terminals: {
      plus: { x: 41, y: 10 },
      minus: { x: 79, y: 10 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_3aaa: {
    width: 138,
    height: 168,
    terminals: {
      plus: { x: 31, y: 10 },
      minus: { x: 107, y: 151 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: 1 },
    },
  },
  battery_4aaa: {
    width: 176,
    height: 154,
    terminals: {
      plus: { x: 31, y: 10 },
      minus: { x: 145, y: 10 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_1c: {
    width: 120,
    height: 182,
    terminals: {
      plus: { x: 60, y: 10 },
      minus: { x: 60, y: 165 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: 1 },
    },
  },
  battery_1d: {
    width: 120,
    height: 204,
    terminals: {
      plus: { x: 60, y: 10 },
      minus: { x: 60, y: 187 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: 1 },
    },
  },
  battery_2d: {
    width: 172,
    height: 190,
    terminals: {
      plus: { x: 49, y: 10 },
      minus: { x: 123, y: 10 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_2aa_nimh: {
    width: 120,
    height: 168,
    terminals: {
      plus: { x: 36, y: 10 },
      minus: { x: 84, y: 10 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_3aa_nimh: {
    width: 168,
    height: 182,
    terminals: {
      plus: { x: 36, y: 10 },
      minus: { x: 132, y: 165 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: 1 },
    },
  },
  battery_4aa_nimh: {
    width: 216,
    height: 168,
    terminals: {
      plus: { x: 36, y: 10 },
      minus: { x: 180, y: 10 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_6aa_nimh: {
    width: 288,
    height: 168,
    terminals: {
      plus: { x: 34, y: 10 },
      minus: { x: 254, y: 10 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_2aaa_nimh: {
    width: 120,
    height: 154,
    terminals: {
      plus: { x: 41, y: 10 },
      minus: { x: 79, y: 10 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_3aaa_nimh: {
    width: 138,
    height: 168,
    terminals: {
      plus: { x: 31, y: 10 },
      minus: { x: 107, y: 151 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: 1 },
    },
  },
  battery_4aaa_nimh: {
    width: 176,
    height: 154,
    terminals: {
      plus: { x: 31, y: 10 },
      minus: { x: 145, y: 10 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_2aa_lithium: {
    width: 120,
    height: 168,
    terminals: {
      plus: { x: 36, y: 10 },
      minus: { x: 84, y: 10 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_3aa_lithium: {
    width: 168,
    height: 182,
    terminals: {
      plus: { x: 36, y: 10 },
      minus: { x: 132, y: 165 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: 1 },
    },
  },
  battery_2aaa_lithium: {
    width: 120,
    height: 154,
    terminals: {
      plus: { x: 41, y: 10 },
      minus: { x: 79, y: 10 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_3aaa_lithium: {
    width: 138,
    height: 168,
    terminals: {
      plus: { x: 31, y: 10 },
      minus: { x: 107, y: 151 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: 1 },
    },
  },
  battery_21700: {
    width: 120,
    height: 180,
    terminals: {
      plus: { x: 60, y: 14 },
      minus: { x: 60, y: 164 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: 1 },
    },
  },
  battery_14500: {
    width: 120,
    height: 180,
    terminals: {
      plus: { x: 60, y: 14 },
      minus: { x: 60, y: 164 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: 1 },
    },
  },
  battery_cr123a: {
    width: 120,
    height: 180,
    terminals: {
      plus: { x: 60, y: 14 },
      minus: { x: 60, y: 164 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: 1 },
    },
  },
  battery_cr2032: {
    width: 160,
    height: 156,
    terminals: {
      plus: { x: 106, y: 17 },
      minus: { x: 54, y: 17 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_lipo_1s: {
    width: 160,
    height: 176,
    terminals: {
      plus: { x: 93, y: 16 },
      minus: { x: 67, y: 16 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  battery_lipo_2s: {
    width: 170,
    height: 178,
    terminals: {
      plus: { x: 101, y: 20 },
      minus: { x: 75, y: 20 },
      plusExit: { dx: 0, dy: -1 },
      minusExit: { dx: 0, dy: -1 },
    },
  },
  supply_barrel_9v: {
    width: 190,
    height: 110,
    terminals: {
      plus: { x: 172, y: 35 },
      minus: { x: 172, y: 69 },
      plusExit: { dx: 1, dy: 0 },
      minusExit: { dx: 1, dy: 0 },
    },
  },
  supply_barrel_12v: {
    width: 190,
    height: 110,
    terminals: {
      plus: { x: 172, y: 35 },
      minus: { x: 172, y: 69 },
      plusExit: { dx: 1, dy: 0 },
      minusExit: { dx: 1, dy: 0 },
    },
  },
} as const satisfies Record<string, BatteryGeometry>;
