import type { CatalogPart } from "./types";

export const boards: CatalogPart[] = [
  {
    id: "board.esp32.devkit",
    name: "ESP32 DevKit",
    kind: "board",
    description: "Wi-Fi + Bluetooth MCU board, 3.3V logic.",
    photoHint: "esp32-devkit",
    pins: [
      { id: "3v3", label: "3V3", kinds: ["power"], voltage: "3v3" },
      { id: "gnd", label: "GND", kinds: ["ground"] },
      { id: "vin", label: "VIN", kinds: ["power"], voltage: "5v" },
      { id: "gpio2", label: "GPIO2", kinds: ["digital"] },
      { id: "gpio4", label: "GPIO4", kinds: ["digital"] },
      { id: "gpio5", label: "GPIO5", kinds: ["digital"] },
      { id: "gpio15", label: "GPIO15", kinds: ["digital"] },
      { id: "gpio16", label: "GPIO16", kinds: ["digital"] },
      { id: "gpio17", label: "GPIO17", kinds: ["digital"] },
      { id: "gpio18", label: "GPIO18", kinds: ["digital"] },
      { id: "gpio19", label: "GPIO19", kinds: ["digital"] },
      { id: "gpio21", label: "GPIO21", kinds: ["digital", "i2c"] },
      { id: "gpio22", label: "GPIO22", kinds: ["digital", "i2c"] },
      { id: "gpio23", label: "GPIO23", kinds: ["digital"] },
      { id: "gpio25", label: "GPIO25", kinds: ["digital", "analog"] },
      { id: "gpio26", label: "GPIO26", kinds: ["digital", "analog"] },
      { id: "gpio27", label: "GPIO27", kinds: ["digital"] },
      { id: "gpio32", label: "GPIO32", kinds: ["digital", "analog"] },
      { id: "gpio33", label: "GPIO33", kinds: ["digital", "analog"] },
      { id: "gpio34", label: "GPIO34", kinds: ["analog"] },
      { id: "gpio35", label: "GPIO35", kinds: ["analog"] },
    ],
  },
  {
    id: "board.pico.rp2040",
    name: "Raspberry Pi Pico",
    kind: "board",
    description: "RP2040 board, 3.3V logic.",
    photoHint: "pico",
    pins: [
      { id: "3v3", label: "3V3", kinds: ["power"], voltage: "3v3" },
      { id: "gnd", label: "GND", kinds: ["ground"] },
      { id: "vbus", label: "VBUS", kinds: ["power"], voltage: "5v" },
      { id: "gp0", label: "GP0", kinds: ["digital", "uart"] },
      { id: "gp1", label: "GP1", kinds: ["digital", "uart"] },
      { id: "gp2", label: "GP2", kinds: ["digital", "i2c"] },
      { id: "gp3", label: "GP3", kinds: ["digital", "i2c"] },
      { id: "gp4", label: "GP4", kinds: ["digital"] },
      { id: "gp5", label: "GP5", kinds: ["digital"] },
      { id: "gp6", label: "GP6", kinds: ["digital"] },
      { id: "gp7", label: "GP7", kinds: ["digital"] },
      { id: "gp15", label: "GP15", kinds: ["digital"] },
      { id: "gp16", label: "GP16", kinds: ["digital"] },
      { id: "gp17", label: "GP17", kinds: ["digital"] },
      { id: "gp26", label: "GP26", kinds: ["digital", "analog"] },
      { id: "gp27", label: "GP27", kinds: ["digital", "analog"] },
      { id: "gp28", label: "GP28", kinds: ["digital", "analog"] },
    ],
  },
  {
    id: "board.arduino.uno",
    name: "Arduino Uno",
    kind: "board",
    description: "ATmega328P Uno, 5V logic.",
    photoHint: "arduino-uno",
    pins: [
      { id: "5v", label: "5V", kinds: ["power"], voltage: "5v" },
      { id: "3v3", label: "3.3V", kinds: ["power"], voltage: "3v3" },
      { id: "gnd", label: "GND", kinds: ["ground"] },
      { id: "vin", label: "VIN", kinds: ["power"], voltage: "5v" },
      { id: "d2", label: "D2", kinds: ["digital"] },
      { id: "d3", label: "D3", kinds: ["digital"] },
      { id: "d4", label: "D4", kinds: ["digital"] },
      { id: "d5", label: "D5", kinds: ["digital"] },
      { id: "d6", label: "D6", kinds: ["digital"] },
      { id: "d7", label: "D7", kinds: ["digital"] },
      { id: "d8", label: "D8", kinds: ["digital"] },
      { id: "d9", label: "D9", kinds: ["digital"] },
      { id: "d10", label: "D10", kinds: ["digital"] },
      { id: "d11", label: "D11", kinds: ["digital"] },
      { id: "d12", label: "D12", kinds: ["digital"] },
      { id: "d13", label: "D13", kinds: ["digital"] },
      { id: "a0", label: "A0", kinds: ["analog", "digital"] },
      { id: "a1", label: "A1", kinds: ["analog", "digital"] },
      { id: "a2", label: "A2", kinds: ["analog", "digital"] },
      { id: "a4", label: "A4", kinds: ["analog", "digital", "i2c"] },
      { id: "a5", label: "A5", kinds: ["analog", "digital", "i2c"] },
    ],
  },
  {
    id: "board.arduino.nano",
    name: "Arduino Nano",
    kind: "board",
    description: "Compact ATmega328P Nano, 5V logic.",
    photoHint: "arduino-nano",
    pins: [
      { id: "5v", label: "5V", kinds: ["power"], voltage: "5v" },
      { id: "3v3", label: "3V3", kinds: ["power"], voltage: "3v3" },
      { id: "gnd", label: "GND", kinds: ["ground"] },
      { id: "vin", label: "VIN", kinds: ["power"], voltage: "5v" },
      { id: "d2", label: "D2", kinds: ["digital"] },
      { id: "d3", label: "D3", kinds: ["digital"] },
      { id: "d4", label: "D4", kinds: ["digital"] },
      { id: "d5", label: "D5", kinds: ["digital"] },
      { id: "d6", label: "D6", kinds: ["digital"] },
      { id: "d7", label: "D7", kinds: ["digital"] },
      { id: "d8", label: "D8", kinds: ["digital"] },
      { id: "d9", label: "D9", kinds: ["digital"] },
      { id: "d10", label: "D10", kinds: ["digital"] },
      { id: "d11", label: "D11", kinds: ["digital"] },
      { id: "d12", label: "D12", kinds: ["digital"] },
      { id: "d13", label: "D13", kinds: ["digital"] },
      { id: "a0", label: "A0", kinds: ["analog", "digital"] },
      { id: "a1", label: "A1", kinds: ["analog", "digital"] },
      { id: "a2", label: "A2", kinds: ["analog", "digital"] },
      { id: "a4", label: "A4", kinds: ["analog", "digital", "i2c"] },
      { id: "a5", label: "A5", kinds: ["analog", "digital", "i2c"] },
    ],
  },
  {
    id: "board.esp8266.nodemcu",
    name: "ESP8266 NodeMCU",
    kind: "board",
    description: "Wi-Fi MCU board, 3.3V logic.",
    photoHint: "esp8266-nodemcu",
    pins: [
      { id: "3v3", label: "3V", kinds: ["power"], voltage: "3v3" },
      { id: "gnd", label: "GND", kinds: ["ground"] },
      { id: "vin", label: "VIN", kinds: ["power"], voltage: "5v" },
      { id: "d0", label: "D0", kinds: ["digital"] },
      { id: "d1", label: "D1", kinds: ["digital", "i2c"] },
      { id: "d2", label: "D2", kinds: ["digital", "i2c"] },
      { id: "d3", label: "D3", kinds: ["digital"] },
      { id: "d4", label: "D4", kinds: ["digital"] },
      { id: "d5", label: "D5", kinds: ["digital"] },
      { id: "d6", label: "D6", kinds: ["digital"] },
      { id: "d7", label: "D7", kinds: ["digital"] },
      { id: "d8", label: "D8", kinds: ["digital"] },
      { id: "a0", label: "A0", kinds: ["analog"] },
    ],
  },
];
