import type { CatalogPart } from "./types";

function power(id: string, label: string, voltage?: "3v3" | "5v") {
  return { id, label, kinds: ["power" as const], voltage };
}
function gnd(id: string, label = "GND") {
  return { id, label, kinds: ["ground" as const] };
}
function dig(id: string, label?: string) {
  return { id, label: label ?? id, kinds: ["digital" as const] };
}
function ana(id: string, label?: string) {
  return { id, label: label ?? id, kinds: ["analog" as const, "digital" as const] };
}

export const boards: CatalogPart[] = [
  {
    id: "board.esp32.devkit",
    name: "ESP32 DevKit V1",
    kind: "board",
    description: "Unofficial ESP32 DevKit V1, 3.3V logic. Wokwi MIT visual.",
    photoHint: "esp32-devkit",
    wokwi: { tag: "wokwi-esp32-devkit-v1" },
    pins: [
      power("VIN", "VIN", "5v"),
      gnd("GND.2", "GND"),
      dig("D13"),
      dig("D12"),
      dig("D14"),
      dig("D27"),
      dig("D26"),
      dig("D25"),
      dig("D33"),
      dig("D32"),
      ana("D35"),
      ana("D34"),
      dig("VN"),
      dig("VP"),
      dig("EN"),
      power("3V3", "3V3", "3v3"),
      gnd("GND.1", "GND"),
      dig("D15"),
      dig("D2"),
      dig("D4"),
      dig("RX2"),
      dig("TX2"),
      { id: "D5", label: "D5", kinds: ["digital", "spi"] },
      { id: "D18", label: "D18", kinds: ["digital", "spi"] },
      { id: "D19", label: "D19", kinds: ["digital", "spi"] },
      { id: "D21", label: "D21", kinds: ["digital", "i2c"] },
      dig("RX0"),
      dig("TX0"),
      { id: "D22", label: "D22", kinds: ["digital", "i2c"] },
      { id: "D23", label: "D23", kinds: ["digital", "spi"] },
    ],
  },
  {
    id: "board.arduino.uno",
    name: "Arduino Uno",
    kind: "board",
    description: "Arduino Uno R3 look, 5V logic. Wokwi MIT visual.",
    photoHint: "arduino-uno",
    wokwi: { tag: "wokwi-arduino-uno" },
    pins: [
      dig("0", "D0"),
      dig("1", "D1"),
      dig("2", "D2"),
      dig("3", "D3"),
      dig("4", "D4"),
      dig("5", "D5"),
      dig("6", "D6"),
      dig("7", "D7"),
      dig("8", "D8"),
      dig("9", "D9"),
      { id: "10", label: "D10", kinds: ["digital", "spi"] },
      { id: "11", label: "D11", kinds: ["digital", "spi"] },
      { id: "12", label: "D12", kinds: ["digital", "spi"] },
      { id: "13", label: "D13", kinds: ["digital", "spi"] },
      ana("A0"),
      ana("A1"),
      ana("A2"),
      ana("A3"),
      { id: "A4", label: "A4", kinds: ["analog", "digital", "i2c"] },
      { id: "A5", label: "A5", kinds: ["analog", "digital", "i2c"] },
      power("5V", "5V", "5v"),
      power("3.3V", "3.3V", "3v3"),
      gnd("GND.1", "GND"),
      gnd("GND.2", "GND"),
      gnd("GND.3", "GND"),
      power("VIN", "VIN", "5v"),
    ],
  },
  {
    id: "board.arduino.nano",
    name: "Arduino Nano",
    kind: "board",
    description: "Arduino Nano look, 5V logic. Wokwi MIT visual.",
    photoHint: "arduino-nano",
    wokwi: { tag: "wokwi-arduino-nano" },
    pins: [
      dig("0", "D0"),
      dig("1", "D1"),
      dig("2", "D2"),
      dig("3", "D3"),
      dig("4", "D4"),
      dig("5", "D5"),
      dig("6", "D6"),
      dig("7", "D7"),
      dig("8", "D8"),
      dig("9", "D9"),
      { id: "10", label: "D10", kinds: ["digital", "spi"] },
      { id: "11", label: "D11", kinds: ["digital", "spi"] },
      { id: "12", label: "D12", kinds: ["digital", "spi"] },
      { id: "13", label: "D13", kinds: ["digital", "spi"] },
      ana("A0"),
      ana("A1"),
      ana("A2"),
      ana("A3"),
      { id: "A4", label: "A4", kinds: ["analog", "digital", "i2c"] },
      { id: "A5", label: "A5", kinds: ["analog", "digital", "i2c"] },
      power("5V", "5V", "5v"),
      power("3.3V", "3.3V", "3v3"),
      gnd("GND.1", "GND"),
      power("VIN", "VIN", "5v"),
    ],
  },
  {
    id: "board.arduino.mega",
    name: "Arduino Mega",
    kind: "board",
    description: "Arduino Mega 2560 look. Wokwi MIT visual.",
    photoHint: "arduino-mega",
    wokwi: { tag: "wokwi-arduino-mega" },
    pins: [
      dig("0", "D0"),
      dig("1", "D1"),
      dig("2", "D2"),
      dig("13", "D13"),
      ana("A0"),
      { id: "20", label: "D20/SDA", kinds: ["digital", "i2c"] },
      { id: "21", label: "D21/SCL", kinds: ["digital", "i2c"] },
      power("5V", "5V", "5v"),
      power("3.3V", "3.3V", "3v3"),
      gnd("GND.1", "GND"),
      power("VIN", "VIN", "5v"),
    ],
  },
  {
    id: "board.pico.rp2040",
    name: "Raspberry Pi Pico",
    kind: "board",
    description: "RP2040 Pico. Skeleton visual until a MIT Wokwi part exists.",
    photoHint: "pico",
    pins: [
      power("3v3", "3V3", "3v3"),
      gnd("gnd", "GND"),
      power("vbus", "VBUS", "5v"),
      dig("gp0", "GP0"),
      dig("gp1", "GP1"),
      { id: "gp2", label: "GP2", kinds: ["digital", "i2c"] },
      { id: "gp3", label: "GP3", kinds: ["digital", "i2c"] },
      dig("gp15", "GP15"),
      ana("gp26", "GP26"),
      ana("gp27", "GP27"),
      ana("gp28", "GP28"),
    ],
  },
  {
    id: "board.esp8266.nodemcu",
    name: "ESP8266 NodeMCU",
    kind: "board",
    description: "NodeMCU ESP8266. Skeleton visual until a MIT Wokwi part exists.",
    photoHint: "esp8266-nodemcu",
    pins: [
      power("3v3", "3V", "3v3"),
      gnd("gnd", "GND"),
      power("vin", "VIN", "5v"),
      dig("d0", "D0"),
      { id: "d1", label: "D1", kinds: ["digital", "i2c"] },
      { id: "d2", label: "D2", kinds: ["digital", "i2c"] },
      dig("d3", "D3"),
      dig("d4", "D4"),
      dig("d5", "D5"),
      dig("d6", "D6"),
      dig("d7", "D7"),
      dig("d8", "D8"),
      ana("a0", "A0"),
    ],
  },
];
