import type { CatalogPart, PartElectrical, VoltageRange } from "./types";

const baseModules: CatalogPart[] = [
  {
    id: "module.buzzer.active",
    name: "Buzzer",
    kind: "module",
    description: "Active buzzer: it beeps by itself when switched on. Pin 1 goes to a GPIO pin on the board, pin 2 goes to ground. A passive buzzer needs a different, tone-playing setup and will not behave the same, so buy an active one.",
    photoHint: "buzzer-active",
    wokwi: { tag: "wokwi-buzzer" },
    pins: [
      { id: "1", label: "1 (SIG)", kinds: ["digital"] },
      { id: "2", label: "2 (GND)", kinds: ["ground"] },
    ],
  },
  {
    id: "module.lcd.i2c.1602",
    name: "LCD 1602 (I2C)",
    kind: "module",
    description: "Small 16x2 text screen with a little circuit board on the back, so it needs only 4 wires.",
    photoHint: "lcd-1602-i2c",
    displayClass: "character-lcd",
    wokwi: { tag: "wokwi-lcd1602", attrs: { pins: "i2c", text: "Hello World" } },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "SDA", label: "SDA", kinds: ["i2c"] },
      { id: "SCL", label: "SCL", kinds: ["i2c"] },
    ],
  },
  {
    id: "module.lcd.parallel.1602",
    name: "LCD 1602 (parallel)",
    kind: "module",
    description: "Small 16x2 text screen with a full row of pins (needs more wires than the I2C kind).",
    photoHint: "lcd-1602",
    displayClass: "character-lcd",
    wokwi: { tag: "wokwi-lcd1602", attrs: { pins: "full", text: "Hello World" } },
    pins: [
      { id: "VSS", label: "VSS", kinds: ["ground"] },
      { id: "VDD", label: "VDD", kinds: ["power"], voltage: "5v" },
      { id: "V0", label: "V0", kinds: ["analog"] },
      { id: "RS", label: "RS", kinds: ["digital"] },
      { id: "RW", label: "RW", kinds: ["digital"] },
      { id: "E", label: "E", kinds: ["digital"] },
      { id: "D4", label: "D4", kinds: ["digital"] },
      { id: "D5", label: "D5", kinds: ["digital"] },
      { id: "D6", label: "D6", kinds: ["digital"] },
      { id: "D7", label: "D7", kinds: ["digital"] },
      { id: "A", label: "A", kinds: ["power"], voltage: "5v" },
      { id: "K", label: "K", kinds: ["ground"] },
    ],
  },
  {
    id: "module.lcd.i2c.2004",
    name: "LCD 2004 (I2C)",
    kind: "module",
    description: "Larger 20x4 text screen with a little circuit board on the back, so it needs only 4 wires.",
    photoHint: "lcd-2004-i2c",
    displayClass: "character-lcd",
    wokwi: { tag: "wokwi-lcd2004", attrs: { pins: "i2c", text: "Hello 20x4 LCD" } },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "SDA", label: "SDA", kinds: ["i2c"] },
      { id: "SCL", label: "SCL", kinds: ["i2c"] },
    ],
  },
  {
    id: "module.lcd.parallel.2004",
    name: "LCD 2004 (parallel)",
    kind: "module",
    description: "Larger 20x4 text screen with a full row of pins (needs more wires than the I2C kind).",
    photoHint: "lcd-2004",
    displayClass: "character-lcd",
    wokwi: { tag: "wokwi-lcd2004", attrs: { pins: "full", text: "Hello 20x4 LCD" } },
    pins: [
      { id: "VSS", label: "VSS", kinds: ["ground"] },
      { id: "VDD", label: "VDD", kinds: ["power"], voltage: "5v" },
      { id: "V0", label: "V0", kinds: ["analog"] },
      { id: "RS", label: "RS", kinds: ["digital"] },
      { id: "RW", label: "RW", kinds: ["digital"] },
      { id: "E", label: "E", kinds: ["digital"] },
      { id: "D4", label: "D4", kinds: ["digital"] },
      { id: "D5", label: "D5", kinds: ["digital"] },
      { id: "D6", label: "D6", kinds: ["digital"] },
      { id: "D7", label: "D7", kinds: ["digital"] },
      { id: "A", label: "A", kinds: ["power"], voltage: "5v" },
      { id: "K", label: "K", kinds: ["ground"] },
    ],
  },
  {
    id: "module.oled.ssd1306",
    name: "OLED SSD1306",
    kind: "module",
    description: "Small 128x64 pixel display. On the I2C kind, DATA connects to SDA and CLK connects to SCL.",
    photoHint: "ssd1306",
    displayClass: "oled",
    wokwi: { tag: "wokwi-ssd1306" },
    pins: [
      { id: "DATA", label: "DATA/SDA", kinds: ["i2c"] },
      { id: "CLK", label: "CLK/SCL", kinds: ["i2c"] },
      { id: "DC", label: "DC", kinds: ["digital"] },
      { id: "RST", label: "RST", kinds: ["digital"] },
      { id: "CS", label: "CS", kinds: ["spi"] },
      { id: "3V3", label: "3V3", kinds: ["power"], voltage: "3v3" },
      { id: "VIN", label: "VIN", kinds: ["power"], voltage: "5v" },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.tft.ili9341",
    name: "TFT ILI9341",
    kind: "module",
    description: "Small color screen (ILI9341 chip) for text and pictures.",
    photoHint: "ili9341",
    displayClass: "tft",
    wokwi: { tag: "wokwi-ili9341" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "3v3" },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "CS", label: "CS", kinds: ["spi", "digital"] },
      { id: "RST", label: "RST", kinds: ["digital"] },
      { id: "D/C", label: "D/C", kinds: ["digital"] },
      { id: "MOSI", label: "MOSI", kinds: ["spi", "digital"] },
      { id: "SCK", label: "SCK", kinds: ["spi", "digital"] },
      { id: "LED", label: "LED", kinds: ["power"], voltage: "3v3" },
      { id: "MISO", label: "MISO", kinds: ["spi", "digital"] },
    ],
  },
  {
    id: "module.soil.moisture",
    name: "Capacitive Soil Moisture Probe",
    kind: "module",
    description:
      "Capacitive soil moisture PCB (corrosion-resistant vs resistive probes). AO analog read and optional DO digital threshold. Custom SVG skeleton for diagram layout.",
    photoHint: "soil-moisture-capacitive",
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "3v3" },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "AO", label: "AO", kinds: ["analog"] },
      { id: "DO", label: "DO", kinds: ["digital"] },
    ],
  },
  {
    id: "module.dht22",
    name: "DHT22 Temp/Humidity",
    kind: "module",
    description: "Measures air temperature and humidity.",
    photoHint: "dht22",
    wokwi: { tag: "wokwi-dht22" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "3v3" },
      { id: "SDA", label: "DATA", kinds: ["digital"] },
      { id: "NC", label: "NC", kinds: ["digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.hc-sr04",
    name: "HC-SR04 Ultrasonic",
    kind: "module",
    description: "Measures distance to an object using sound.",
    photoHint: "hc-sr04",
    wokwi: { tag: "wokwi-hc-sr04" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "TRIG", label: "TRIG", kinds: ["digital"] },
      { id: "ECHO", label: "ECHO", kinds: ["digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.servo",
    name: "Servo Motor",
    kind: "module",
    description: "Small motor that turns to a set angle (for example 0 to 180 degrees).",
    photoHint: "servo",
    wokwi: { tag: "wokwi-servo" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "V+", label: "V+", kinds: ["power"], voltage: "5v" },
      { id: "PWM", label: "PWM/SIG", kinds: ["digital"] },
    ],
  },
  {
    id: "module.neopixel",
    name: "NeoPixel",
    kind: "module",
    description: "Color LED you can set to any color from your board.",
    photoHint: "neopixel",
    wokwi: { tag: "wokwi-neopixel" },
    pins: [
      { id: "VDD", label: "VDD", kinds: ["power"], voltage: "5v" },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
      { id: "VSS", label: "VSS", kinds: ["ground"] },
      { id: "DIN", label: "DIN", kinds: ["digital"] },
    ],
  },
  {
    id: "module.rgb-led",
    name: "RGB LED",
    kind: "module",
    description: "LED that can show any color by mixing red, green and blue.",
    photoHint: "rgb-led",
    wokwi: { tag: "wokwi-rgb-led" },
    pins: [
      { id: "R", label: "R", kinds: ["digital"] },
      { id: "COM", label: "COM", kinds: ["ground"] },
      { id: "G", label: "G", kinds: ["digital"] },
      { id: "B", label: "B", kinds: ["digital"] },
    ],
  },
  {
    id: "module.pir.motion",
    name: "PIR Motion Sensor",
    kind: "module",
    description: "Detects when a person or animal moves in front of it.",
    photoHint: "pir-motion",
    wokwi: { tag: "wokwi-pir-motion-sensor" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "OUT", label: "OUT", kinds: ["digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.photoresistor",
    name: "Photoresistor Module",
    kind: "module",
    description: "Light sensor. Its reading changes with how bright the room is.",
    photoHint: "photoresistor",
    wokwi: { tag: "wokwi-photoresistor-sensor" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "DO", label: "DO", kinds: ["digital"] },
      { id: "AO", label: "AO", kinds: ["analog"] },
    ],
  },
  {
    id: "module.ntc.temperature",
    name: "NTC Temperature Module",
    kind: "module",
    description: "Temperature sensor. Its reading changes as it gets warmer or cooler.",
    photoHint: "ntc-temperature",
    wokwi: { tag: "wokwi-ntc-temperature-sensor" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "OUT", label: "OUT", kinds: ["analog"] },
    ],
  },
  {
    id: "module.flame",
    name: "Flame Sensor",
    kind: "module",
    description: "Detects the glow of a flame nearby.",
    photoHint: "flame-sensor",
    wokwi: { tag: "wokwi-flame-sensor" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
      { id: "AOUT", label: "AOUT", kinds: ["analog"] },
    ],
  },
  {
    id: "module.gas",
    name: "Gas Sensor (MQ)",
    kind: "module",
    description: "Detects smoke or combustible gas in the air.",
    photoHint: "gas-sensor",
    wokwi: { tag: "wokwi-gas-sensor" },
    pins: [
      { id: "AOUT", label: "AOUT", kinds: ["analog"] },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
    ],
  },
  {
    id: "module.mpu6050",
    name: "MPU6050 IMU",
    kind: "module",
    description: "Senses movement and tilt. Talks to the board over 4 wires (I2C).",
    photoHint: "mpu6050",
    wokwi: { tag: "wokwi-mpu6050" },
    pins: [
      { id: "INT", label: "INT", kinds: ["digital"] },
      { id: "AD0", label: "AD0", kinds: ["digital"] },
      { id: "XCL", label: "XCL", kinds: ["i2c"] },
      { id: "XDA", label: "XDA", kinds: ["i2c"] },
      { id: "SDA", label: "SDA", kinds: ["i2c"] },
      { id: "SCL", label: "SCL", kinds: ["i2c"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "3v3" },
    ],
  },
  {
    id: "module.hx711",
    name: "HX711 Load Cell Amp",
    kind: "module",
    description: "Small board that reads a weight sensor (load cell) and passes the number to your board.",
    photoHint: "hx711",
    wokwi: { tag: "wokwi-hx711" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "DT", label: "DT", kinds: ["digital"] },
      { id: "SCK", label: "SCK", kinds: ["digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.heart.beat",
    name: "Heartbeat (Pulse) Sensor",
    kind: "module",
    description: "Reads your pulse when a fingertip rests on it.",
    photoHint: "heart-beat",
    wokwi: { tag: "wokwi-heart-beat-sensor" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "OUT", label: "OUT", kinds: ["digital", "analog"] },
    ],
  },
  {
    id: "module.big.sound",
    name: "Big Sound Sensor",
    kind: "module",
    description: "Microphone that picks up sound and boosts it (larger board).",
    photoHint: "big-sound",
    wokwi: { tag: "wokwi-big-sound-sensor" },
    pins: [
      { id: "AOUT", label: "AOUT", kinds: ["analog"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
    ],
  },
  {
    id: "module.small.sound",
    name: "Small Sound Sensor",
    kind: "module",
    description: "Small microphone that picks up sound.",
    photoHint: "small-sound",
    wokwi: { tag: "wokwi-small-sound-sensor" },
    pins: [
      { id: "AOUT", label: "AOUT", kinds: ["analog"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
    ],
  },
  {
    id: "module.ir.receiver",
    name: "IR Receiver",
    kind: "module",
    description: "Receives signals from an infrared remote control.",
    photoHint: "ir-receiver",
    wokwi: { tag: "wokwi-ir-receiver" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "DAT", label: "DAT", kinds: ["digital"] },
    ],
  },
  {
    id: "module.analog.joystick",
    name: "Analog Joystick",
    kind: "module",
    description: "Thumb joystick that senses left, right, up and down, and clicks when pressed.",
    photoHint: "analog-joystick",
    wokwi: { tag: "wokwi-analog-joystick" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "VERT", label: "VERT", kinds: ["analog"] },
      { id: "HORZ", label: "HORZ", kinds: ["analog"] },
      { id: "SEL", label: "SEL", kinds: ["digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.ky.040",
    name: "KY-040 Rotary Encoder",
    kind: "module",
    description: "Knob that senses how far and which way you turn it, and clicks when pressed.",
    photoHint: "ky-040",
    wokwi: { tag: "wokwi-ky-040" },
    pins: [
      { id: "CLK", label: "CLK", kinds: ["digital"] },
      { id: "DT", label: "DT", kinds: ["digital"] },
      { id: "SW", label: "SW", kinds: ["digital"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.ds1307",
    name: "DS1307 RTC",
    kind: "module",
    description: "Keeps the time even when the power is off, using a small coin battery (CR2032).",
    photoHint: "ds1307",
    wokwi: { tag: "wokwi-ds1307" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "5V", label: "5V", kinds: ["power"], voltage: "5v" },
      { id: "SDA", label: "SDA", kinds: ["i2c"] },
      { id: "SCL", label: "SCL", kinds: ["i2c"] },
      { id: "SQW", label: "SQW", kinds: ["digital"] },
    ],
  },
  {
    id: "module.tilt.switch",
    name: "Tilt Switch Module",
    kind: "module",
    description: "Switch that turns on or off when you tilt it.",
    photoHint: "tilt-switch",
    wokwi: { tag: "wokwi-tilt-switch" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "OUT", label: "OUT", kinds: ["digital"] },
    ],
  },
  {
    id: "module.membrane.keypad",
    name: "Membrane Keypad 4×4",
    kind: "module",
    description: "Flat keypad with 16 buttons and 8 pins.",
    photoHint: "membrane-keypad",
    wokwi: { tag: "wokwi-membrane-keypad", attrs: { columns: "4" } },
    pins: [
      { id: "R1", label: "R1", kinds: ["digital"] },
      { id: "R2", label: "R2", kinds: ["digital"] },
      { id: "R3", label: "R3", kinds: ["digital"] },
      { id: "R4", label: "R4", kinds: ["digital"] },
      { id: "C1", label: "C1", kinds: ["digital"] },
      { id: "C2", label: "C2", kinds: ["digital"] },
      { id: "C3", label: "C3", kinds: ["digital"] },
      { id: "C4", label: "C4", kinds: ["digital"] },
    ],
  },
  {
    id: "module.microsd",
    name: "microSD Card Module",
    kind: "module",
    description: "Holds a microSD card so your project can save and read files.",
    photoHint: "microsd",
    wokwi: { tag: "wokwi-microsd-card" },
    pins: [
      { id: "CD", label: "CD", kinds: ["digital"] },
      { id: "DO", label: "DO", kinds: ["spi", "digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "SCK", label: "SCK", kinds: ["spi", "digital"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "3v3" },
      { id: "DI", label: "DI", kinds: ["spi", "digital"] },
      { id: "CS", label: "CS", kinds: ["spi", "digital"] },
    ],
  },
  {
    id: "module.led.bar.graph",
    name: "LED Bar Graph",
    kind: "module",
    description: "Row of 10 small lights, like a level meter.",
    photoHint: "led-bar-graph",
    wokwi: { tag: "wokwi-led-bar-graph" },
    pins: [
      { id: "A1", label: "A1", kinds: ["digital"] },
      { id: "A2", label: "A2", kinds: ["digital"] },
      { id: "A3", label: "A3", kinds: ["digital"] },
      { id: "A4", label: "A4", kinds: ["digital"] },
      { id: "A5", label: "A5", kinds: ["digital"] },
      { id: "A6", label: "A6", kinds: ["digital"] },
      { id: "A7", label: "A7", kinds: ["digital"] },
      { id: "A8", label: "A8", kinds: ["digital"] },
      { id: "A9", label: "A9", kinds: ["digital"] },
      { id: "A10", label: "A10", kinds: ["digital"] },
      { id: "C1", label: "C1", kinds: ["digital"] },
      { id: "C2", label: "C2", kinds: ["digital"] },
      { id: "C3", label: "C3", kinds: ["digital"] },
      { id: "C4", label: "C4", kinds: ["digital"] },
      { id: "C5", label: "C5", kinds: ["digital"] },
      { id: "C6", label: "C6", kinds: ["digital"] },
      { id: "C7", label: "C7", kinds: ["digital"] },
      { id: "C8", label: "C8", kinds: ["digital"] },
      { id: "C9", label: "C9", kinds: ["digital"] },
      { id: "C10", label: "C10", kinds: ["digital"] },
    ],
  },
  {
    id: "module.stepper.motor",
    name: "Stepper Motor (NEMA)",
    kind: "module",
    description: "Motor that turns in precise steps. Has four wires.",
    photoHint: "stepper-motor",
    wokwi: { tag: "wokwi-stepper-motor" },
    pins: [
      { id: "A-", label: "A−", kinds: ["digital"] },
      { id: "A+", label: "A+", kinds: ["digital"] },
      { id: "B+", label: "B+", kinds: ["digital"] },
      { id: "B-", label: "B−", kinds: ["digital"] },
    ],
  },
  {
    id: "module.7segment",
    name: "7-Segment Display",
    kind: "module",
    description: "Shows one number from 0 to 9 using lit bars.",
    photoHint: "7segment",
    wokwi: { tag: "wokwi-7segment", attrs: { digits: "1" } },
    pins: [
      { id: "COM.1", label: "COM.1", kinds: ["digital", "power"] },
      { id: "COM.2", label: "COM.2", kinds: ["digital", "power"] },
      { id: "A", label: "A", kinds: ["digital"] },
      { id: "B", label: "B", kinds: ["digital"] },
      { id: "C", label: "C", kinds: ["digital"] },
      { id: "D", label: "D", kinds: ["digital"] },
      { id: "E", label: "E", kinds: ["digital"] },
      { id: "F", label: "F", kinds: ["digital"] },
      { id: "G", label: "G", kinds: ["digital"] },
      { id: "DP", label: "DP", kinds: ["digital"] },
    ],
  },
  {
    id: "module.dip.switch.8",
    name: "DIP Switch (8-position)",
    kind: "module",
    description: "Row of 8 tiny on/off switches.",
    photoHint: "dip-switch-8",
    wokwi: { tag: "wokwi-dip-switch-8" },
    pins: [
      { id: "1a", label: "1a", kinds: ["digital"] },
      { id: "2a", label: "2a", kinds: ["digital"] },
      { id: "3a", label: "3a", kinds: ["digital"] },
      { id: "4a", label: "4a", kinds: ["digital"] },
      { id: "5a", label: "5a", kinds: ["digital"] },
      { id: "6a", label: "6a", kinds: ["digital"] },
      { id: "7a", label: "7a", kinds: ["digital"] },
      { id: "8a", label: "8a", kinds: ["digital"] },
      { id: "8b", label: "8b", kinds: ["digital"] },
      { id: "7b", label: "7b", kinds: ["digital"] },
      { id: "6b", label: "6b", kinds: ["digital"] },
      { id: "5b", label: "5b", kinds: ["digital"] },
      { id: "4b", label: "4b", kinds: ["digital"] },
      { id: "3b", label: "3b", kinds: ["digital"] },
      { id: "2b", label: "2b", kinds: ["digital"] },
      { id: "1b", label: "1b", kinds: ["digital"] },
    ],
  },
  {
    id: "module.slide.switch",
    name: "Slide Switch",
    kind: "module",
    description: "Slide switch with three pins that picks between two connections.",
    photoHint: "slide-switch",
    wokwi: { tag: "wokwi-slide-switch" },
    pins: [
      { id: "1", label: "1", kinds: ["digital"] },
      { id: "2", label: "2", kinds: ["digital"] },
      { id: "3", label: "3", kinds: ["digital"] },
    ],
  },
  {
    id: "module.slide.potentiometer",
    name: "Slide Potentiometer",
    kind: "module",
    description: "Slider you push back and forth to give a variable value, like a volume fader.",
    photoHint: "slide-potentiometer",
    wokwi: { tag: "wokwi-slide-potentiometer" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "SIG", label: "SIG", kinds: ["analog"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.neopixel.matrix",
    name: "NeoPixel Matrix",
    kind: "module",
    description: "Grid of color LEDs you can light individually.",
    photoHint: "neopixel-matrix",
    wokwi: { tag: "wokwi-neopixel-matrix" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "DIN", label: "DIN", kinds: ["digital"] },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
    ],
  },
  {
    id: "module.led.ring",
    name: "NeoPixel LED Ring",
    kind: "module",
    description: "Ring of color LEDs you can light individually.",
    photoHint: "led-ring",
    wokwi: { tag: "wokwi-led-ring" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "DIN", label: "DIN", kinds: ["digital"] },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
    ],
  },
  {
    id: "module.biaxial.stepper",
    name: "Biaxial Stepper (Gauge)",
    kind: "module",
    description: "Small motor with two coils, used to move the needle on a gauge.",
    photoHint: "biaxial-stepper",
    wokwi: { tag: "wokwi-biaxial-stepper" },
    pins: [
      { id: "A1-", label: "A1−", kinds: ["digital"] },
      { id: "A1+", label: "A1+", kinds: ["digital"] },
      { id: "B1+", label: "B1+", kinds: ["digital"] },
      { id: "B1-", label: "B1−", kinds: ["digital"] },
      { id: "A2-", label: "A2−", kinds: ["digital"] },
      { id: "A2+", label: "A2+", kinds: ["digital"] },
      { id: "B2+", label: "B2+", kinds: ["digital"] },
      { id: "B2-", label: "B2−", kinds: ["digital"] },
    ],
  },
  {
    id: "module.relay.ks2e",
    name: "KS2E Relay (DPDT)",
    kind: "module",
    description: "Small electrically controlled switch, with two sets of contacts.",
    photoHint: "relay-ks2e",
    wokwi: { tag: "wokwi-ks2e-m-dc5" },
    pins: [
      { id: "NO2", label: "NO2", kinds: ["digital"] },
      { id: "NC2", label: "NC2", kinds: ["digital"] },
      { id: "P2", label: "P2", kinds: ["digital"] },
      { id: "COIL2", label: "COIL2", kinds: ["digital", "ground"] },
      { id: "NO1", label: "NO1", kinds: ["digital"] },
      { id: "NC1", label: "NC1", kinds: ["digital"] },
      { id: "P1", label: "P1", kinds: ["digital"] },
      { id: "COIL1", label: "COIL1", kinds: ["digital"] },
    ],
  },
];

const V5: VoltageRange = { min: 4.5, max: 5.5 };
const V3_3_ONLY: VoltageRange = { min: 3.0, max: 3.6 };
/** Typical LM393-style sensor breakout. */
const V3_5: VoltageRange = { min: 3.3, max: 5.5 };

const lcdI2c: PartElectrical = {
  supply: V5,
  logic: "5v",
  logicFollowsSupply: true,
  inputHighFraction: 0.7,
};

const lcdParallel: PartElectrical = {
  supply: V5,
  logic: "5v",
  inputOnlyPins: ["RS", "RW", "E", "D4", "D5", "D6", "D7", "V0"],
  inputHighVolts: 2.2,
};

const neopixel: PartElectrical = {
  supply: { min: 3.5, max: 5.3 },
  logic: "5v",
  logicFollowsSupply: true,
  inputOnlyPins: ["DIN"],
  inputHighFraction: 0.7,
};

const sensor3v5: PartElectrical = { supply: V3_5, logic: "5v", logicFollowsSupply: true };

const MODULE_ELECTRICAL: Record<string, PartElectrical> = {
  "module.lcd.i2c.1602": lcdI2c,
  "module.lcd.i2c.2004": lcdI2c,
  "module.lcd.parallel.1602": lcdParallel,
  "module.lcd.parallel.2004": lcdParallel,
  "module.oled.ssd1306": {
    logic: "3v3",
    pins: {
      "3V3": { accepts: V3_3_ONLY },
      VIN: { accepts: V3_5 },
    },
    inputOnlyPins: ["CLK", "DC", "RST", "CS"],
    inputMaxVolts: 3.6,
    inputMaxIsHard: false,
  },
  "module.tft.ili9341": {
    logic: "3v3",
    supply: V3_3_ONLY,
    inputOnlyPins: ["CS", "RST", "D/C", "MOSI", "SCK"],
    inputMaxVolts: 3.6,
  },
  "module.soil.moisture": sensor3v5,
  "module.dht22": { supply: { min: 3.0, max: 6 }, logic: "5v", logicFollowsSupply: true },
  "module.hc-sr04": { supply: V5, logic: "5v", inputOnlyPins: ["TRIG"] },
  "module.servo": { supply: { min: 4.5, max: 6 }, logic: "5v", inputOnlyPins: ["PWM"] },
  "module.neopixel": neopixel,
  "module.neopixel.matrix": neopixel,
  "module.led.ring": neopixel,
  // HC-SR501 style: wide input range, regulated 3.3V output.
  "module.pir.motion": { supply: { min: 4.5, max: 12 }, logic: "3v3" },
  "module.photoresistor": sensor3v5,
  "module.ntc.temperature": sensor3v5,
  "module.flame": sensor3v5,
  "module.gas": { supply: V5, logic: "5v", logicFollowsSupply: true },
  // GY-521 style breakout with onboard LDO; the I2C pins are not level shifted.
  "module.mpu6050": {
    supply: { min: 3.0, max: 5.5 },
    logic: "3v3",
    inputOnlyPins: ["AD0", "XCL", "XDA"],
    inputMaxVolts: 3.6,
    inputMaxIsHard: false,
  },
  "module.hx711": {
    supply: { min: 2.7, max: 5.5 },
    logic: "5v",
    logicFollowsSupply: true,
    inputOnlyPins: ["SCK"],
  },
  "module.heart.beat": sensor3v5,
  "module.big.sound": sensor3v5,
  "module.small.sound": sensor3v5,
  "module.ir.receiver": { supply: { min: 2.5, max: 5.5 }, logic: "5v", logicFollowsSupply: true },
  "module.analog.joystick": sensor3v5,
  "module.ky.040": sensor3v5,
  "module.ds1307": {
    supply: V5,
    logic: "5v",
    logicFollowsSupply: true,
    inputHighVolts: 2.2,
  },
  "module.tilt.switch": sensor3v5,
  "module.microsd": {
    logic: "3v3",
    supply: V3_3_ONLY,
    inputOnlyPins: ["CS", "SCK", "DI"],
    inputMaxVolts: 3.6,
  },
  "module.slide.potentiometer": sensor3v5,
};

export const modules: CatalogPart[] = baseModules.map((part) => ({
  ...part,
  electrical: MODULE_ELECTRICAL[part.id],
}));
