import type { CatalogPart } from "./types";

export const modules: CatalogPart[] = [
  {
    id: "module.buzzer.active",
    name: "Buzzer",
    kind: "module",
    description: "Passive/active buzzer look. Wokwi MIT visual. Pin 1 signal, pin 2 GND.",
    photoHint: "buzzer-active",
    wokwi: { tag: "wokwi-buzzer" },
    pins: [
      { id: "1", label: "1 (SIG)", kinds: ["digital"] },
      { id: "2", label: "2 (GND)", kinds: ["ground"] },
    ],
  },
  {
    id: "module.lcd.i2c.1602",
    name: "LCD 1602 (I2C)",
    kind: "module",
    description: "16x2 character LCD class with I2C backpack. Wokwi MIT visual.",
    photoHint: "lcd-1602-i2c",
    displayClass: "character-lcd",
    wokwi: { tag: "wokwi-lcd1602", attrs: { pins: "i2c", text: "Hello World" } },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "SDA", label: "SDA", kinds: ["i2c"] },
      { id: "SCL", label: "SCL", kinds: ["i2c"] },
    ],
  },
  {
    id: "module.lcd.parallel.1602",
    name: "LCD 1602 (parallel)",
    kind: "module",
    description: "16x2 HD44780 character LCD, full pin header. Wokwi MIT visual.",
    photoHint: "lcd-1602",
    displayClass: "character-lcd",
    wokwi: { tag: "wokwi-lcd1602", attrs: { pins: "full", text: "Hello World" } },
    pins: [
      { id: "VSS", label: "VSS", kinds: ["ground"] },
      { id: "VDD", label: "VDD", kinds: ["power"], voltage: "5v" },
      { id: "V0", label: "V0", kinds: ["analog"] },
      { id: "RS", label: "RS", kinds: ["digital"] },
      { id: "RW", label: "RW", kinds: ["digital"] },
      { id: "E", label: "E", kinds: ["digital"] },
      { id: "D4", label: "D4", kinds: ["digital"] },
      { id: "D5", label: "D5", kinds: ["digital"] },
      { id: "D6", label: "D6", kinds: ["digital"] },
      { id: "D7", label: "D7", kinds: ["digital"] },
      { id: "A", label: "A", kinds: ["power"], voltage: "5v" },
      { id: "K", label: "K", kinds: ["ground"] },
    ],
  },
  {
    id: "module.lcd.i2c.2004",
    name: "LCD 2004 (I2C)",
    kind: "module",
    description: "20x4 character LCD class with I2C backpack. Wokwi MIT visual.",
    photoHint: "lcd-2004-i2c",
    displayClass: "character-lcd",
    wokwi: { tag: "wokwi-lcd2004", attrs: { pins: "i2c", text: "Hello 20x4 LCD" } },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "SDA", label: "SDA", kinds: ["i2c"] },
      { id: "SCL", label: "SCL", kinds: ["i2c"] },
    ],
  },
  {
    id: "module.lcd.parallel.2004",
    name: "LCD 2004 (parallel)",
    kind: "module",
    description: "20x4 HD44780 character LCD, full pin header. Wokwi MIT visual.",
    photoHint: "lcd-2004",
    displayClass: "character-lcd",
    wokwi: { tag: "wokwi-lcd2004", attrs: { pins: "full", text: "Hello 20x4 LCD" } },
    pins: [
      { id: "VSS", label: "VSS", kinds: ["ground"] },
      { id: "VDD", label: "VDD", kinds: ["power"], voltage: "5v" },
      { id: "V0", label: "V0", kinds: ["analog"] },
      { id: "RS", label: "RS", kinds: ["digital"] },
      { id: "RW", label: "RW", kinds: ["digital"] },
      { id: "E", label: "E", kinds: ["digital"] },
      { id: "D4", label: "D4", kinds: ["digital"] },
      { id: "D5", label: "D5", kinds: ["digital"] },
      { id: "D6", label: "D6", kinds: ["digital"] },
      { id: "D7", label: "D7", kinds: ["digital"] },
      { id: "A", label: "A", kinds: ["power"], voltage: "5v" },
      { id: "K", label: "K", kinds: ["ground"] },
    ],
  },
  {
    id: "module.oled.ssd1306",
    name: "OLED SSD1306",
    kind: "module",
    description: "128x64 OLED class. DATA/CLK map to SDA/SCL on I2C modules. Wokwi MIT visual.",
    photoHint: "ssd1306",
    displayClass: "oled",
    wokwi: { tag: "wokwi-ssd1306" },
    pins: [
      { id: "DATA", label: "DATA/SDA", kinds: ["i2c"] },
      { id: "CLK", label: "CLK/SCL", kinds: ["i2c"] },
      { id: "DC", label: "DC", kinds: ["digital"] },
      { id: "RST", label: "RST", kinds: ["digital"] },
      { id: "CS", label: "CS", kinds: ["spi"] },
      { id: "3V3", label: "3V3", kinds: ["power"], voltage: "3v3" },
      { id: "VIN", label: "VIN", kinds: ["power"], voltage: "5v" },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.tft.ili9341",
    name: "TFT ILI9341",
    kind: "module",
    description: "Color TFT class (ILI9341 family). Wokwi MIT visual.",
    photoHint: "ili9341",
    displayClass: "tft",
    wokwi: { tag: "wokwi-ili9341" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "3v3" },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "CS", label: "CS", kinds: ["spi", "digital"] },
      { id: "RST", label: "RST", kinds: ["digital"] },
      { id: "D/C", label: "D/C", kinds: ["digital"] },
      { id: "MOSI", label: "MOSI", kinds: ["spi", "digital"] },
      { id: "SCK", label: "SCK", kinds: ["spi", "digital"] },
      { id: "LED", label: "LED", kinds: ["power"], voltage: "3v3" },
      { id: "MISO", label: "MISO", kinds: ["spi", "digital"] },
    ],
  },
  {
    id: "module.soil.moisture",
    name: "Capacitive Soil Moisture Probe",
    kind: "module",
    description:
      "Capacitive soil moisture PCB (corrosion-resistant vs resistive probes). AO analog read and optional DO digital threshold. Custom SVG skeleton for diagram layout.",
    photoHint: "soil-moisture-capacitive",
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "3v3" },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "AO", label: "AO", kinds: ["analog"] },
      { id: "DO", label: "DO", kinds: ["digital"] },
    ],
  },
  {
    id: "module.dht22",
    name: "DHT22 Temp/Humidity",
    kind: "module",
    description: "Digital temperature and humidity sensor. Wokwi MIT visual.",
    photoHint: "dht22",
    wokwi: { tag: "wokwi-dht22" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "3v3" },
      { id: "SDA", label: "DATA", kinds: ["digital"] },
      { id: "NC", label: "NC", kinds: ["digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.hc-sr04",
    name: "HC-SR04 Ultrasonic",
    kind: "module",
    description: "Ultrasonic distance sensor. Wokwi MIT visual.",
    photoHint: "hc-sr04",
    wokwi: { tag: "wokwi-hc-sr04" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "TRIG", label: "TRIG", kinds: ["digital"] },
      { id: "ECHO", label: "ECHO", kinds: ["digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.servo",
    name: "Servo Motor",
    kind: "module",
    description: "Hobby servo (PWM). Wokwi MIT visual.",
    photoHint: "servo",
    wokwi: { tag: "wokwi-servo" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "V+", label: "V+", kinds: ["power"], voltage: "5v" },
      { id: "PWM", label: "PWM/SIG", kinds: ["digital"] },
    ],
  },
  {
    id: "module.neopixel",
    name: "NeoPixel",
    kind: "module",
    description: "Addressable RGB LED (WS2812). Wokwi MIT visual.",
    photoHint: "neopixel",
    wokwi: { tag: "wokwi-neopixel" },
    pins: [
      { id: "VDD", label: "VDD", kinds: ["power"], voltage: "5v" },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
      { id: "VSS", label: "VSS", kinds: ["ground"] },
      { id: "DIN", label: "DIN", kinds: ["digital"] },
    ],
  },
  {
    id: "module.rgb-led",
    name: "RGB LED",
    kind: "module",
    description: "Common-cathode RGB LED. Wokwi MIT visual.",
    photoHint: "rgb-led",
    wokwi: { tag: "wokwi-rgb-led" },
    pins: [
      { id: "R", label: "R", kinds: ["digital"] },
      { id: "COM", label: "COM", kinds: ["ground"] },
      { id: "G", label: "G", kinds: ["digital"] },
      { id: "B", label: "B", kinds: ["digital"] },
    ],
  },
  {
    id: "module.pir.motion",
    name: "PIR Motion Sensor",
    kind: "module",
    description: "Passive infrared motion detector module. Wokwi MIT visual.",
    photoHint: "pir-motion",
    wokwi: { tag: "wokwi-pir-motion-sensor" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "OUT", label: "OUT", kinds: ["digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.photoresistor",
    name: "Photoresistor Module",
    kind: "module",
    description: "Light-dependent resistor breakout with AO/DO. Wokwi MIT visual.",
    photoHint: "photoresistor",
    wokwi: { tag: "wokwi-photoresistor-sensor" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "DO", label: "DO", kinds: ["digital"] },
      { id: "AO", label: "AO", kinds: ["analog"] },
    ],
  },
  {
    id: "module.ntc.temperature",
    name: "NTC Temperature Module",
    kind: "module",
    description: "Thermistor temperature sensor breakout. Wokwi MIT visual.",
    photoHint: "ntc-temperature",
    wokwi: { tag: "wokwi-ntc-temperature-sensor" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "OUT", label: "OUT", kinds: ["analog"] },
    ],
  },
  {
    id: "module.flame",
    name: "Flame Sensor",
    kind: "module",
    description: "Infrared flame detection module. Wokwi MIT visual.",
    photoHint: "flame-sensor",
    wokwi: { tag: "wokwi-flame-sensor" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
      { id: "AOUT", label: "AOUT", kinds: ["analog"] },
    ],
  },
  {
    id: "module.gas",
    name: "Gas Sensor (MQ)",
    kind: "module",
    description: "Combustible gas sensor module (MQ family). Wokwi MIT visual.",
    photoHint: "gas-sensor",
    wokwi: { tag: "wokwi-gas-sensor" },
    pins: [
      { id: "AOUT", label: "AOUT", kinds: ["analog"] },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
    ],
  },
  {
    id: "module.mpu6050",
    name: "MPU6050 IMU",
    kind: "module",
    description: "6-axis accelerometer and gyroscope (I2C). Wokwi MIT visual.",
    photoHint: "mpu6050",
    wokwi: { tag: "wokwi-mpu6050" },
    pins: [
      { id: "INT", label: "INT", kinds: ["digital"] },
      { id: "AD0", label: "AD0", kinds: ["digital"] },
      { id: "XCL", label: "XCL", kinds: ["i2c"] },
      { id: "XDA", label: "XDA", kinds: ["i2c"] },
      { id: "SDA", label: "SDA", kinds: ["i2c"] },
      { id: "SCL", label: "SCL", kinds: ["i2c"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "3v3" },
    ],
  },
  {
    id: "module.hx711",
    name: "HX711 Load Cell Amp",
    kind: "module",
    description: "24-bit ADC for load cells and strain gauges. Wokwi MIT visual.",
    photoHint: "hx711",
    wokwi: { tag: "wokwi-hx711" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "DT", label: "DT", kinds: ["digital"] },
      { id: "SCK", label: "SCK", kinds: ["digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.heart.beat",
    name: "Heartbeat (Pulse) Sensor",
    kind: "module",
    description: "Optical pulse / heart-rate sensor module. Wokwi MIT visual.",
    photoHint: "heart-beat",
    wokwi: { tag: "wokwi-heart-beat-sensor" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "OUT", label: "OUT", kinds: ["digital", "analog"] },
    ],
  },
  {
    id: "module.big.sound",
    name: "Big Sound Sensor",
    kind: "module",
    description: "Electret microphone amplifier (large board). Wokwi MIT visual.",
    photoHint: "big-sound",
    wokwi: { tag: "wokwi-big-sound-sensor" },
    pins: [
      { id: "AOUT", label: "AOUT", kinds: ["analog"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
    ],
  },
  {
    id: "module.small.sound",
    name: "Small Sound Sensor",
    kind: "module",
    description: "Compact microphone sound module. Wokwi MIT visual.",
    photoHint: "small-sound",
    wokwi: { tag: "wokwi-small-sound-sensor" },
    pins: [
      { id: "AOUT", label: "AOUT", kinds: ["analog"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
    ],
  },
  {
    id: "module.ir.receiver",
    name: "IR Receiver",
    kind: "module",
    description: "38 kHz infrared receiver (TSOP class). Wokwi MIT visual.",
    photoHint: "ir-receiver",
    wokwi: { tag: "wokwi-ir-receiver" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "DAT", label: "DAT", kinds: ["digital"] },
    ],
  },
  {
    id: "module.analog.joystick",
    name: "Analog Joystick",
    kind: "module",
    description: "Dual-axis analog joystick with push button. Wokwi MIT visual.",
    photoHint: "analog-joystick",
    wokwi: { tag: "wokwi-analog-joystick" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "VERT", label: "VERT", kinds: ["analog"] },
      { id: "HORZ", label: "HORZ", kinds: ["analog"] },
      { id: "SEL", label: "SEL", kinds: ["digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.ky.040",
    name: "KY-040 Rotary Encoder",
    kind: "module",
    description: "Rotary encoder with integrated push switch. Wokwi MIT visual.",
    photoHint: "ky-040",
    wokwi: { tag: "wokwi-ky-040" },
    pins: [
      { id: "CLK", label: "CLK", kinds: ["digital"] },
      { id: "DT", label: "DT", kinds: ["digital"] },
      { id: "SW", label: "SW", kinds: ["digital"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.ds1307",
    name: "DS1307 RTC",
    kind: "module",
    description: "Real-time clock module (I2C, CR2032 holder). Wokwi MIT visual.",
    photoHint: "ds1307",
    wokwi: { tag: "wokwi-ds1307" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "5V", label: "5V", kinds: ["power"], voltage: "5v" },
      { id: "SDA", label: "SDA", kinds: ["i2c"] },
      { id: "SCL", label: "SCL", kinds: ["i2c"] },
      { id: "SQW", label: "SQW", kinds: ["digital"] },
    ],
  },
  {
    id: "module.tilt.switch",
    name: "Tilt Switch Module",
    kind: "module",
    description: "Ball tilt switch breakout. Wokwi MIT visual.",
    photoHint: "tilt-switch",
    wokwi: { tag: "wokwi-tilt-switch" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "OUT", label: "OUT", kinds: ["digital"] },
    ],
  },
  {
    id: "module.membrane.keypad",
    name: "Membrane Keypad 4×4",
    kind: "module",
    description: "4×4 matrix membrane keypad (8-pin header). Wokwi MIT visual.",
    photoHint: "membrane-keypad",
    wokwi: { tag: "wokwi-membrane-keypad", attrs: { columns: "4" } },
    pins: [
      { id: "R1", label: "R1", kinds: ["digital"] },
      { id: "R2", label: "R2", kinds: ["digital"] },
      { id: "R3", label: "R3", kinds: ["digital"] },
      { id: "R4", label: "R4", kinds: ["digital"] },
      { id: "C1", label: "C1", kinds: ["digital"] },
      { id: "C2", label: "C2", kinds: ["digital"] },
      { id: "C3", label: "C3", kinds: ["digital"] },
      { id: "C4", label: "C4", kinds: ["digital"] },
    ],
  },
  {
    id: "module.microsd",
    name: "microSD Card Module",
    kind: "module",
    description: "SPI microSD card breakout. Wokwi MIT visual.",
    photoHint: "microsd",
    wokwi: { tag: "wokwi-microsd-card" },
    pins: [
      { id: "CD", label: "CD", kinds: ["digital"] },
      { id: "DO", label: "DO", kinds: ["spi", "digital"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "SCK", label: "SCK", kinds: ["spi", "digital"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "3v3" },
      { id: "DI", label: "DI", kinds: ["spi", "digital"] },
      { id: "CS", label: "CS", kinds: ["spi", "digital"] },
    ],
  },
  {
    id: "module.led.bar.graph",
    name: "LED Bar Graph",
    kind: "module",
    description: "10-segment LED bar graph (dual 5-pin headers). Wokwi MIT visual.",
    photoHint: "led-bar-graph",
    wokwi: { tag: "wokwi-led-bar-graph" },
    pins: [
      { id: "A1", label: "A1", kinds: ["digital"] },
      { id: "A2", label: "A2", kinds: ["digital"] },
      { id: "A3", label: "A3", kinds: ["digital"] },
      { id: "A4", label: "A4", kinds: ["digital"] },
      { id: "A5", label: "A5", kinds: ["digital"] },
      { id: "A6", label: "A6", kinds: ["digital"] },
      { id: "A7", label: "A7", kinds: ["digital"] },
      { id: "A8", label: "A8", kinds: ["digital"] },
      { id: "A9", label: "A9", kinds: ["digital"] },
      { id: "A10", label: "A10", kinds: ["digital"] },
      { id: "C1", label: "C1", kinds: ["digital"] },
      { id: "C2", label: "C2", kinds: ["digital"] },
      { id: "C3", label: "C3", kinds: ["digital"] },
      { id: "C4", label: "C4", kinds: ["digital"] },
      { id: "C5", label: "C5", kinds: ["digital"] },
      { id: "C6", label: "C6", kinds: ["digital"] },
      { id: "C7", label: "C7", kinds: ["digital"] },
      { id: "C8", label: "C8", kinds: ["digital"] },
      { id: "C9", label: "C9", kinds: ["digital"] },
      { id: "C10", label: "C10", kinds: ["digital"] },
    ],
  },
  {
    id: "module.stepper.motor",
    name: "Stepper Motor (NEMA)",
    kind: "module",
    description: "Bipolar stepper motor (four coil wires). Wokwi MIT visual.",
    photoHint: "stepper-motor",
    wokwi: { tag: "wokwi-stepper-motor" },
    pins: [
      { id: "A-", label: "A−", kinds: ["digital"] },
      { id: "A+", label: "A+", kinds: ["digital"] },
      { id: "B+", label: "B+", kinds: ["digital"] },
      { id: "B-", label: "B−", kinds: ["digital"] },
    ],
  },
  {
    id: "module.7segment",
    name: "7-Segment Display",
    kind: "module",
    description: "Single-digit 7-segment LED (common pinout). Wokwi MIT visual.",
    photoHint: "7segment",
    wokwi: { tag: "wokwi-7segment", attrs: { digits: "1" } },
    pins: [
      { id: "COM.1", label: "COM.1", kinds: ["digital", "power"] },
      { id: "COM.2", label: "COM.2", kinds: ["digital", "power"] },
      { id: "A", label: "A", kinds: ["digital"] },
      { id: "B", label: "B", kinds: ["digital"] },
      { id: "C", label: "C", kinds: ["digital"] },
      { id: "D", label: "D", kinds: ["digital"] },
      { id: "E", label: "E", kinds: ["digital"] },
      { id: "F", label: "F", kinds: ["digital"] },
      { id: "G", label: "G", kinds: ["digital"] },
      { id: "DP", label: "DP", kinds: ["digital"] },
    ],
  },
  {
    id: "module.dip.switch.8",
    name: "DIP Switch (8-position)",
    kind: "module",
    description: "Eight-position through-hole DIP switch. Wokwi MIT visual.",
    photoHint: "dip-switch-8",
    wokwi: { tag: "wokwi-dip-switch-8" },
    pins: [
      { id: "1a", label: "1a", kinds: ["digital"] },
      { id: "2a", label: "2a", kinds: ["digital"] },
      { id: "3a", label: "3a", kinds: ["digital"] },
      { id: "4a", label: "4a", kinds: ["digital"] },
      { id: "5a", label: "5a", kinds: ["digital"] },
      { id: "6a", label: "6a", kinds: ["digital"] },
      { id: "7a", label: "7a", kinds: ["digital"] },
      { id: "8a", label: "8a", kinds: ["digital"] },
      { id: "8b", label: "8b", kinds: ["digital"] },
      { id: "7b", label: "7b", kinds: ["digital"] },
      { id: "6b", label: "6b", kinds: ["digital"] },
      { id: "5b", label: "5b", kinds: ["digital"] },
      { id: "4b", label: "4b", kinds: ["digital"] },
      { id: "3b", label: "3b", kinds: ["digital"] },
      { id: "2b", label: "2b", kinds: ["digital"] },
      { id: "1b", label: "1b", kinds: ["digital"] },
    ],
  },
  {
    id: "module.slide.switch",
    name: "Slide Switch",
    kind: "module",
    description: "SPDT slide switch (three terminals). Wokwi MIT visual.",
    photoHint: "slide-switch",
    wokwi: { tag: "wokwi-slide-switch" },
    pins: [
      { id: "1", label: "1", kinds: ["digital"] },
      { id: "2", label: "2", kinds: ["digital"] },
      { id: "3", label: "3", kinds: ["digital"] },
    ],
  },
  {
    id: "module.slide.potentiometer",
    name: "Slide Potentiometer",
    kind: "module",
    description: "Linear slide pot for faders and analog input. Wokwi MIT visual.",
    photoHint: "slide-potentiometer",
    wokwi: { tag: "wokwi-slide-potentiometer" },
    pins: [
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "SIG", label: "SIG", kinds: ["analog"] },
      { id: "GND", label: "GND", kinds: ["ground"] },
    ],
  },
  {
    id: "module.neopixel.matrix",
    name: "NeoPixel Matrix",
    kind: "module",
    description: "WS2812 addressable LED matrix panel. Wokwi MIT visual.",
    photoHint: "neopixel-matrix",
    wokwi: { tag: "wokwi-neopixel-matrix" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "DIN", label: "DIN", kinds: ["digital"] },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
    ],
  },
  {
    id: "module.led.ring",
    name: "NeoPixel LED Ring",
    kind: "module",
    description: "Circular WS2812 LED ring. Wokwi MIT visual.",
    photoHint: "led-ring",
    wokwi: { tag: "wokwi-led-ring" },
    pins: [
      { id: "GND", label: "GND", kinds: ["ground"] },
      { id: "VCC", label: "VCC", kinds: ["power"], voltage: "5v" },
      { id: "DIN", label: "DIN", kinds: ["digital"] },
      { id: "DOUT", label: "DOUT", kinds: ["digital"] },
    ],
  },
  {
    id: "module.biaxial.stepper",
    name: "Biaxial Stepper (Gauge)",
    kind: "module",
    description: "Dual-coil meter movement / biaxial stepper for analog gauges. Wokwi MIT visual.",
    photoHint: "biaxial-stepper",
    wokwi: { tag: "wokwi-biaxial-stepper" },
    pins: [
      { id: "A1-", label: "A1−", kinds: ["digital"] },
      { id: "A1+", label: "A1+", kinds: ["digital"] },
      { id: "B1+", label: "B1+", kinds: ["digital"] },
      { id: "B1-", label: "B1−", kinds: ["digital"] },
      { id: "A2-", label: "A2−", kinds: ["digital"] },
      { id: "A2+", label: "A2+", kinds: ["digital"] },
      { id: "B2+", label: "B2+", kinds: ["digital"] },
      { id: "B2-", label: "B2−", kinds: ["digital"] },
    ],
  },
  {
    id: "module.relay.ks2e",
    name: "KS2E Relay (DPDT)",
    kind: "module",
    description: "Omron KS2E-class signal relay (two poles). Wokwi MIT visual.",
    photoHint: "relay-ks2e",
    wokwi: { tag: "wokwi-ks2e-m-dc5" },
    pins: [
      { id: "NO2", label: "NO2", kinds: ["digital"] },
      { id: "NC2", label: "NC2", kinds: ["digital"] },
      { id: "P2", label: "P2", kinds: ["digital"] },
      { id: "COIL2", label: "COIL2", kinds: ["digital", "ground"] },
      { id: "NO1", label: "NO1", kinds: ["digital"] },
      { id: "NC1", label: "NC1", kinds: ["digital"] },
      { id: "P1", label: "P1", kinds: ["digital"] },
      { id: "COIL1", label: "COIL1", kinds: ["digital"] },
    ],
  },
];
