import { EXTRA_BASICS_QUERIES } from "./extra/basics-queries";
import { EXTRA_OUTPUTS_QUERIES } from "./extra/outputs-queries";
import { EXTRA_DISPLAYS_QUERIES } from "./extra/displays-queries";
import { EXTRA_SENSORS_QUERIES } from "./extra/sensors-queries";
import { EXTRA_BOARDS_QUERIES } from "./extra/boards-queries";
import type { PhotoQueriesOverride } from "./types";

/** Bundled photo search phrases per part id (the seed). Leaf module: no registry import. */
export const SEED_PHOTO_QUERY_OVERRIDES: Record<string, PhotoQueriesOverride> = {
  // Boards
  "board.esp32.devkit": {
    commons: ["ESP32 DevKit", "ESP32 development board"],
    wikipedia: ["ESP32"],
  },
  "board.arduino.uno": ["Arduino Uno R3", "Arduino Uno"],
  "board.arduino.nano": ["Arduino Nano V3", "Arduino Nano -clone"],
  "board.arduino.mega": ["Arduino Mega 2560", "Arduino Mega"],
  "board.pico.rp2040": ["Raspberry Pi Pico -W -WH -2 -Zero", "Raspberry Pi Pico"],
  "board.pico.w": ["Raspberry Pi Pico WH", "Raspberry Pi Pico W"],
  "board.pico.2": ["Raspberry Pi Pico 2"],
  "board.pi.zero.w": ["Raspberry Pi Zero W -2", "Raspberry Pi Zero"],
  "board.pi.3b.plus": ["Raspberry Pi 3 Model B+", "Raspberry Pi 3B+"],
  "board.pi.4b": ["Raspberry Pi 4 Model B"],
  "board.pi.5": ["Raspberry Pi 5 -Pico -Zero", "Raspberry Pi 5"],
  "board.esp8266.nodemcu": { commons: ["NodeMCU ESP8266", "NodeMCU"], wikipedia: ["NodeMCU"] },

  // Modules
  "module.buzzer.active": ["piezo buzzer"],
  "module.lcd.i2c.1602": ["16x2 LCD I2C", "16x2 LCD"],
  "module.lcd.parallel.1602": ["HD44780 16x2", "16x2 LCD"],
  "module.lcd.i2c.2004": ["LCD2004", "20x4 LCD", "LCD 20x4"],
  "module.lcd.parallel.2004": ["LCD2004", "20x4 LCD", "LCD 20x4"],
  "module.oled.ssd1306": ["SSD1306", "SSD1306 OLED"],
  "module.tft.ili9341": ["ILI9341"],
  "module.soil.moisture": ["capacitive soil moisture sensor", "soil moisture sensor"],
  "module.dht22": ["DHT22", "DHT22 sensor"],
  "module.hc-sr04": ["HC-SR04", "HC-SR04 ultrasonic"],
  "module.servo": {
    commons: ["servo motor SG90", "micro servo", "servo motor"],
    wikipedia: ["Servomotor"],
  },
  "module.neopixel": ["NeoPixel", "WS2812B"],
  "module.rgb-led": ["RGB LED"],
  "module.pir.motion": {
    commons: ["PIR sensor", "HC-SR501"],
    wikipedia: ["Passive infrared sensor"],
  },
  "module.photoresistor": {
    commons: ["photoresistor", "LDR photoresistor"],
    wikipedia: ["Photoresistor"],
  },
  "module.ntc.temperature": {
    commons: ["NTC thermistor", "thermistor"],
    wikipedia: ["Thermistor"],
  },
  "module.flame": ["flame detector Arduino", "flame sensor Arduino"],
  "module.gas": ["MQ-2 gas sensor", "MQ-135", "gas sensor Arduino"],
  "module.mpu6050": ["MPU-6050 module", "GY-521", "MPU6050"],
  "module.hx711": ["HX711", "load cell amplifier"],
  "module.heart.beat": ["pulse sensor Arduino", "heart rate sensor Arduino"],
  "module.big.sound": ["KY-038", "sound sensor Arduino"],
  "module.small.sound": ["KY-037", "sound sensor Arduino", "microphone sensor module"],
  "module.ir.receiver": ["TSOP infrared receiver", "IR receiver sensor"],
  "module.analog.joystick": ["thumb joystick", "analog joystick module"],
  "module.ky.040": ["rotary encoder -gray -absolute", "KY-040"],
  "module.ds1307": ["DS1307"],
  "module.tilt.switch": ["tilt switch -mercury -deck", "tilt sensor"],
  "module.membrane.keypad": ["keypad 4x4", "membrane keypad -calculator"],
  "module.microsd": ["microSD breakout", "microSD module"],
  "module.led.bar.graph": ["LED bar graph"],
  "module.stepper.motor": {
    commons: ["NEMA 17 stepper motor -Arduino -CNC", "stepper motor"],
    wikipedia: ["Stepper motor"],
  },
  "module.7segment": {
    commons: ["seven segment display"],
    wikipedia: ["Seven-segment display"],
  },
  "module.dip.switch.8": ["DIP switch -cable -printer", "DIP switch"],
  "module.slide.switch": ["slide switch -cross"],
  "module.slide.potentiometer": ["slide potentiometer", "slider potentiometer"],
  "module.neopixel.matrix": ["NeoPixel matrix", "8x8 LED matrix"],
  "module.led.ring": ["NeoPixel ring", "LED ring"],
  "module.biaxial.stepper": ["VID6606", "VID29 stepper motor"],
  "module.relay.ks2e": ["DPDT relay"],

  // Basic parts and power
  "passive.breadboard.half": { commons: ["breadboard"], wikipedia: ["Breadboard"] },
  "passive.resistor.220": { commons: ["axial lead resistors", "resistor"], wikipedia: ["Resistor"] },
  "passive.resistor.1k": { commons: ["axial lead resistors", "resistor"], wikipedia: ["Resistor"] },
  "passive.resistor.10k": { commons: ["axial lead resistors", "resistor"], wikipedia: ["Resistor"] },
  "passive.led.red": ["5mm red LED -RGB -cycling", "Red LED"],
  "passive.led.green": ["5mm green LED -RGB -cycling", "Green LED"],
  "passive.potentiometer": {
    commons: ["potentiometer", "trimmer potentiometer"],
    wikipedia: ["Potentiometer"],
  },
  "passive.pushbutton": ["tactile switch -keyboard", "Tactile switches"],
  "passive.power.usb_wall": ["USB wall charger", "USB power adapter"],
  "passive.power.battery.9v": ["9-volt battery", "9V battery"],
  "passive.power.battery.2aa": ["2xAA battery holder", "AA battery holder"],
  "passive.power.battery.3aa": ["AA battery holder"],
  "passive.power.battery.18650": ["18650 battery", "18650"],
  "passive.power.power_bank": ["power bank USB", "Powerbank"],
  "passive.power.battery.1aa": ["AA battery", "AA alkaline battery"],
  "passive.power.battery.4aa": ["4xAA battery holder", "AA battery holder"],
  "passive.power.battery.6aa": ["6xAA battery holder", "AA battery holder"],
  "passive.power.battery.2aaa": ["AAA battery holder", "AAA battery"],
  "passive.power.battery.3aaa": ["AAA battery holder", "AAA battery"],
  "passive.power.battery.4aaa": ["AAA battery holder", "AAA battery"],
  "passive.power.battery.1c": ["C battery", "C cell battery"],
  "passive.power.battery.1d": ["D battery", "D cell battery"],
  "passive.power.battery.2d": ["D battery", "D cell battery"],
  "passive.power.battery.2aa_nimh": ["NiMH AA rechargeable battery", "Eneloop AA"],
  "passive.power.battery.3aa_nimh": ["NiMH AA rechargeable battery", "Eneloop AA"],
  "passive.power.battery.4aa_nimh": ["NiMH AA rechargeable battery", "Eneloop AA"],
  "passive.power.battery.6aa_nimh": ["NiMH AA rechargeable battery", "Eneloop AA"],
  "passive.power.battery.2aaa_nimh": ["NiMH AAA rechargeable battery", "AAA rechargeable battery"],
  "passive.power.battery.3aaa_nimh": ["NiMH AAA rechargeable battery", "AAA rechargeable battery"],
  "passive.power.battery.4aaa_nimh": ["NiMH AAA rechargeable battery", "AAA rechargeable battery"],
  "passive.power.battery.2aa_lithium": ["lithium AA battery", "Lithium primary battery AA"],
  "passive.power.battery.3aa_lithium": ["lithium AA battery", "Lithium primary battery AA"],
  "passive.power.battery.2aaa_lithium": ["lithium AAA battery", "Lithium primary battery AAA"],
  "passive.power.battery.3aaa_lithium": ["lithium AAA battery", "Lithium primary battery AAA"],
  "passive.power.battery.cr123a": ["CR123A battery", "CR123A"],
  "passive.power.battery.cr2032": ["CR2032 battery", "CR2032 coin cell"],
  "passive.power.battery.21700": ["21700 battery", "21700 cell"],
  "passive.power.battery.14500": ["14500 battery", "14500 lithium-ion"],
  "passive.power.battery.lipo_1s": ["LiPo battery pouch", "Lithium polymer battery"],
  "passive.power.battery.lipo_2s": ["LiPo battery pack 2S", "Lithium polymer battery pack"],
  "passive.power.supply.barrel_9v": ["9V DC power adapter", "AC adapter barrel plug"],
  "passive.power.supply.barrel_12v": ["12V DC power adapter", "AC adapter barrel plug"],
  ...EXTRA_BASICS_QUERIES,
  ...EXTRA_OUTPUTS_QUERIES,
  ...EXTRA_DISPLAYS_QUERIES,
  ...EXTRA_SENSORS_QUERIES,
  ...EXTRA_BOARDS_QUERIES,
};
