import { EXTRA_BASICS_MEDIA } from "./extra/basics-media";
import { EXTRA_OUTPUTS_MEDIA } from "./extra/outputs-media";
import { EXTRA_DISPLAYS_MEDIA } from "./extra/displays-media";
import { EXTRA_SENSORS_MEDIA } from "./extra/sensors-media";
import { EXTRA_BOARDS_MEDIA } from "./extra/boards-media";
import { BASIC_PART_MEDIA } from "./media-basic";
import { BATTERY_PART_MEDIA } from "./media-batteries";
import { MODULE_PART_MEDIA } from "./media-modules";

/** Bundled photo table (the seed media map). Leaf module: no registry import. */
export const SEED_PHOTO_FILES: Record<string, string> = {
  "arduino-mega": "/photos/arduino-mega.jpg",
  "arduino-nano": "/photos/arduino-nano.jpg",
  "arduino-uno": "/photos/arduino-uno.jpg",
  "battery-18650": "/photos/battery-18650.svg",
  "battery-2aa": "/photos/battery-2aa.svg",
  "battery-3aa": "/photos/battery-3aa.svg",
  "battery-9v": "/photos/battery-9v.svg",
  "biaxial-stepper": "/photos/biaxial-stepper.jpg",
  "breadboard-half": "/photos/breadboard-half.jpg",
  "dht22": "/photos/dht22.jpg",
  "dip-switch-8": "/photos/dip-switch-8.jpg",
  "esp8266-nodemcu": "/photos/esp8266-nodemcu.jpg",
  "esp32-devkit": "/photos/esp32-devkit.svg",
  "lcd-1602": "/photos/lcd-1602.jpg",
  "lcd-1602-i2c": "/photos/lcd-1602-i2c.jpg",
  "lcd-2004": "/photos/lcd-2004.jpg",
  "lcd-2004-i2c": "/photos/lcd-2004-i2c.jpg",
  "led-green": "/photos/led-green.jpg",
  "led-red": "/photos/led-red.jpg",
  "membrane-keypad": "/photos/membrane-keypad.jpg",
  "microsd": "/photos/microsd.jpg",
  "mpu6050": "/photos/mpu6050.jpg",
  "photoresistor": "/photos/photoresistor.jpg",
  "pico": "/photos/pico.jpg",
  "pir-motion": "/photos/pir-motion.jpg",
  "potentiometer": "/photos/potentiometer.jpg",
  "pushbutton": "/photos/pushbutton.jpg",
  "relay-ks2e": "/photos/relay-ks2e.jpg",
  "resistor-10k": "/photos/resistor-10k.jpg",
  "resistor-1k": "/photos/resistor-1k.jpg",
  "resistor-220": "/photos/resistor-220.jpg",
  "rgb-led": "/photos/rgb-led.jpg",
  "servo": "/photos/servo.jpg",
  "ssd1306": "/photos/ssd1306.jpg",
  "stepper-motor": "/photos/stepper-motor.jpg",
  "usb-wall": "/photos/usb-wall.svg",
  "buzzer-active": "/photos/buzzer-active.svg",
  "ili9341": "/photos/ili9341.svg",
  "soil-moisture-capacitive": "/photos/soil-moisture-capacitive.svg",
  "hc-sr04": "/photos/hc-sr04.svg",
  "neopixel": "/photos/neopixel.svg",
  "ntc-temperature": "/photos/ntc-temperature.svg",
  "flame-sensor": "/photos/flame-sensor.svg",
  "gas-sensor": "/photos/gas-sensor.svg",
  "hx711": "/photos/hx711.svg",
  "heart-beat": "/photos/heart-beat.svg",
  "big-sound": "/photos/big-sound.svg",
  "small-sound": "/photos/small-sound.svg",
  "ir-receiver": "/photos/ir-receiver.svg",
  "analog-joystick": "/photos/analog-joystick.svg",
  "ky-040": "/photos/ky-040.svg",
  "ds1307": "/photos/ds1307.svg",
  "tilt-switch": "/photos/tilt-switch.svg",
  "led-bar-graph": "/photos/led-bar-graph.svg",
  "7segment": "/photos/7segment.svg",
  "slide-switch": "/photos/slide-switch.svg",
  "slide-potentiometer": "/photos/slide-potentiometer.svg",
  "neopixel-matrix": "/photos/neopixel-matrix.svg",
  "led-ring": "/photos/led-ring.svg",
  // Newer illustrations; later entries win over the ones above.
  ...BASIC_PART_MEDIA,
  ...MODULE_PART_MEDIA,
  ...BATTERY_PART_MEDIA,
  ...EXTRA_BASICS_MEDIA,
  ...EXTRA_OUTPUTS_MEDIA,
  ...EXTRA_DISPLAYS_MEDIA,
  ...EXTRA_SENSORS_MEDIA,
  ...EXTRA_BOARDS_MEDIA,
};
